defmodule ExTorchTest.DynamicBatchTest do
  @moduledoc """
  Verifies that `torch.export` models exported with a symbolic batch
  dimension (`Dim("batch")`) run correctly at multiple batch sizes
  across all three Export inference paths.

  Covers:
    * A pure Linear/ReLU MLP (no shape arithmetic anywhere)
    * A small ConvNet with conv / BN / pool / flatten / linear
    * A real ResNet18 (69 ATen nodes, residual connections)

  Fixtures generated by `test/fixtures/generate_dynamic_shape_models.py`.
  """
  use ExUnit.Case, async: false

  @fixtures_dir Path.join([__DIR__, "..", "fixtures"])
  @tol_rtol 1.0e-4
  @tol_atol 1.0e-5

  setup_all do
    required = [
      "mlp_dynamic_batch.pt2",
      "convnet_dynamic_batch.pt2",
      "resnet18_dynamic_batch.pt2"
    ]

    missing = Enum.reject(required, &File.exists?(Path.join(@fixtures_dir, &1)))

    if missing != [] do
      flunk(
        "Missing dynamic-batch fixtures: #{inspect(missing)}. " <>
          "Run: .venv/bin/python test/fixtures/generate_dynamic_shape_models.py"
      )
    end

    :ok
  end

  defp read_bin(name, shape) do
    path = Path.join(@fixtures_dir, "#{name}.bin")
    ExTorch.Native.from_binary(File.read!(path), shape, :float32)
  end

  defp load(name), do: ExTorch.Export.load(Path.join(@fixtures_dir, "#{name}.pt2"))

  defp assert_matches(model, name, bs, input_shape, output_shape) do
    input = read_bin("#{name}_input_bs#{bs}", input_shape)
    expected = read_bin("#{name}_output_bs#{bs}", output_shape)

    for {path, runner} <- [
          {"forward/2", fn -> ExTorch.Export.forward(model, [input]) end},
          {"forward_native/2", fn -> ExTorch.Export.forward_native(model, [input]) end},
          {"forward_compiled/2",
           fn ->
             # forward_compiled mutates the model struct; use a fresh load
             m = load(name)
             ExTorch.Export.forward_compiled(m, [input])
           end}
        ] do
      out = runner.()

      assert %ExTorch.Tensor{} = out,
             "#{name} bs=#{bs} #{path}: non-tensor output #{inspect(out)}"

      assert out.size == output_shape,
             "#{name} bs=#{bs} #{path}: got shape #{inspect(out.size)}, want #{inspect(output_shape)}"

      assert ExTorch.allclose(out, expected, @tol_rtol, @tol_atol),
             "#{name} bs=#{bs} #{path}: output diverges from PyTorch reference"
    end
  end

  describe "MLP with dynamic batch" do
    setup do
      {:ok, model: load("mlp_dynamic_batch")}
    end

    test "batch=1", %{model: m},
      do: assert_matches(m, "mlp_dynamic_batch", 1, {1, 10}, {1, 5})

    test "batch=4", %{model: m},
      do: assert_matches(m, "mlp_dynamic_batch", 4, {4, 10}, {4, 5})

    test "batch=8", %{model: m},
      do: assert_matches(m, "mlp_dynamic_batch", 8, {8, 10}, {8, 5})
  end

  describe "ConvNet with dynamic batch" do
    setup do
      {:ok, model: load("convnet_dynamic_batch")}
    end

    test "batch=1", %{model: m},
      do: assert_matches(m, "convnet_dynamic_batch", 1, {1, 3, 8, 8}, {1, 3})

    test "batch=4", %{model: m},
      do: assert_matches(m, "convnet_dynamic_batch", 4, {4, 3, 8, 8}, {4, 3})

    test "batch=8", %{model: m},
      do: assert_matches(m, "convnet_dynamic_batch", 8, {8, 3, 8, 8}, {8, 3})
  end

  describe "ResNet18 with dynamic batch" do
    setup do
      {:ok, model: load("resnet18_dynamic_batch")}
    end

    test "batch=1", %{model: m},
      do: assert_matches(m, "resnet18_dynamic_batch", 1, {1, 3, 224, 224}, {1, 1000})

    test "batch=4", %{model: m},
      do: assert_matches(m, "resnet18_dynamic_batch", 4, {4, 3, 224, 224}, {4, 1000})
  end
end
