name: Linting

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    linux:
        name: Credo linting
        runs-on: ubuntu-latest
        env:
            OTP_VERSION: ${{ matrix.OTP_VERSION }}
            ELIXIR_VERSION: ${{ matrix.ELIXIR_VERSION }}
            PYTORCH_VERSION: ${{ matrix.PYTORCH_VERSION }}
            DEVICE: ${{ matrix.DEVICE }}
            RUNNER_OS: "ubuntu"
        strategy:
            fail-fast: false
            matrix:
                PYTORCH_VERSION: ['latest']
                OTP_VERSION: ['25']
                ELIXIR_VERSION: ['1.15']
                DEVICE: ['cpu']
        steps:
            - name: Checkout branch
              uses: actions/checkout@v1
            - name: Install latest Rust nightly
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                override: true
                components: rustfmt, clippy
            - name: Print Rust version
              shell: bash -l {0}
              run: rustc --version
            - name: Install OTP and Elixir
              uses: erlef/setup-beam@v1
              with:
                otp-version: ${{ matrix.OTP_VERSION }}
                elixir-version: ${{ matrix.ELIXIR_VERSION }}
            - name: Download libtorch binaries
              shell: bash -l {0}
              run: bash -l .github/scripts/download_torch.sh
            - name: Install dependencies
              shell: bash -l {0}
              run: mix deps.get
            - name: Run credo
              shell: bash -l {0}
              run: bash -l .github/scripts/lint_extorch.sh
            # Enable this if SSH debugging is required
            # - name: Setup tmate session
            #   if: ${{ failure() }}
            #   uses: mxschmitt/action-tmate@v3
