name: Linux build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    linux:
        name: Linux OTP${{ matrix.OTP_VERSION }} / Elixir ${{ matrix.ELIXIR_VERSION }} (${{ matrix.PYTORCH_VERSION }} - ${{ matrix.DEVICE }})
        runs-on: ubuntu-latest
        env:
            OTP_VERSION: ${{ matrix.OTP_VERSION }}
            ELIXIR_VERSION: ${{ matrix.ELIXIR_VERSION }}
            PYTORCH_VERSION: ${{ matrix.PYTORCH_VERSION }}
            DEVICE: ${{ matrix.DEVICE }}
            RUNNER_OS: "ubuntu"
        strategy:
            fail-fast: false
            matrix:
                PYTORCH_VERSION: ['2.1.0', 'latest']
                OTP_VERSION: ['26', '25']
                ELIXIR_VERSION: ['1.15', '1.14.5']
                DEVICE: ['cpu']
        steps:
            - name: Checkout branch
              uses: actions/checkout@v3
            - name: Install latest Rust nightly
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                override: true
                components: rustfmt, clippy
            - name: Print Rust version
              shell: bash -l {0}
              run: rustc --version
            - name: Install OTP and Elixir
              uses: erlef/setup-beam@v1
              with:
                otp-version: ${{ matrix.OTP_VERSION }}
                elixir-version: ${{ matrix.ELIXIR_VERSION }}
            - name: Download libtorch binaries
              shell: bash -l {0}
              run: bash -l .github/scripts/download_torch.sh
            - name: Install dependencies
              shell: bash -l {0}
              run: mix deps.get
            # - name: Download libtorch binaries
            #   shell: bash -l {0}
            #   run: mix pull_lib_torch --version ${{ matrix.PYTORCH_VERSION }}
            - name: Build and test extorch
              shell: bash -l {0}
              run: bash -l .github/scripts/test_extorch.sh
            # Enable this if SSH debugging is required
            # - name: Setup tmate session
            #   if: ${{ failure() }}
            #   uses: mxschmitt/action-tmate@v3
